on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username abd00 --password dckr_pat_Abdo&Fared200200
      - name: " building docker "
        run: docker build -t ${{ secrets.}}/docker-image-creation .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKER_USERNAME}}/docker-image-creation .